#!/usr/bin/env python3
"""Emit the Serenity Reboot timeline from the measured alignment.

Same rule as Video 1: scenes are declared by which script lines they cover,
never by timestamp, and every time in the output is read out of aligned.json.
Edit the scene table below to move a cue; never edit the generated file.

Timing comes from the real 4:47 recording, not from the brief's estimated
"7.3 min" - a stated runtime describes an intention, an alignment describes
what was actually said.

Usage:
    python build-serenity.py
"""
import json
import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
AL = json.loads((REPO / "assets/serenity-reboot/aligned.json").read_text())
ANIM = REPO / "remotion/public/serenity-reboot/animations"
NARRATION = REPO / "remotion/public/serenity-reboot/narration.mp3"

TOTAL = round(float(subprocess.run(
    ["ffprobe", "-v", "error", "-show_entries", "format=duration",
     "-of", "csv=p=0", str(NARRATION)],
    capture_output=True, text=True).stdout.strip()) + 0.9, 2)

# (kind, slide number, first line, last line, text beats)
# The slide numbers are the deck's own. Note that 05 precedes 04: the deck
# introduces Serenity Reboot before the "I need a reset" card, but the
# narration names the project first and says the three words after.
SCENES = [
    ("slide", 1,  0, 10, None),
    # The Monday scene is pure staccato and has no slide of its own, so it
    # runs as type - which is also where the cut rate does the most work.
    ("text", None, 11, 25, [[11], [12, 13, 14], [15], [16], [17, 18, 19],
                            [20, 21], [22, 23], [24], [25]]),
    ("slide", 2, 26, 34, None),
    ("slide", 3, 35, 38, None),
    ("slide", 5, 39, 43, None),
    ("slide", 4, 44, 45, None),
    ("slide", 6, 46, 51, None),
    ("slide", 7, 52, 55, None),
    ("slide", 8, 56, 58, None),
    ("slide", 9, 59, 66, None),
    ("slide", 10, 67, 70, None),
    ("slide", 11, 71, 82, None),
    ("slide", 12, 83, 89, None),
    ("slide", 13, 90, 93, None),
    # The affiliate disclosure gets the screen to itself, in plain type.
    ("text", None, 94, 95, [[94], [95]]),
    ("slide", 14, 96, 109, None),
    ("slide", 15, 110, 117, None),
    ("end", None, 118, 118, None),
]

# Lines set in the display face, in brand pink.
EMPHASIS = {20, 24, 25}


def boundary(prev_last, next_first):
    a, b = AL[prev_last]["end"], AL[next_first]["start"]
    return round((a + b) / 2, 2) if b > a else round(b, 2)


starts = [0.0]
for i in range(1, len(SCENES)):
    starts.append(boundary(SCENES[i - 1][3], SCENES[i][2]))
ends = starts[1:] + [TOTAL]

out = []
for (kind, slide, lo, hi, beats), s, e in zip(SCENES, starts, ends):
    if kind == "slide":
        scene = {
            "kind": "slide",
            "image": f"serenity-reboot/slides/{slide:02d}.jpg",
            "from": round(s, 2),
            "to": round(e, 2),
            "say": AL[lo]["text"],
        }
        clip = ANIM / f"{slide:02d}.mp4"
        if clip.exists():
            scene["video"] = f"serenity-reboot/animations/{slide:02d}.mp4"
            scene["videoLast"] = f"serenity-reboot/animations/{slide:02d}-last.png"
            scene["videoSeconds"] = round(float(subprocess.run(
                ["ffprobe", "-v", "error", "-show_entries", "format=duration",
                 "-of", "csv=p=0", str(clip)],
                capture_output=True, text=True).stdout.strip()), 2)
        out.append(scene)
    elif kind == "end":
        span = AL[118]["end"] - AL[118]["start"]
        t0 = AL[118]["start"]
        out.append({
            "kind": "end",
            "from": round(s, 2),
            "to": round(e, 2),
            "beats": [
                {"at": round(t0, 2), "lines": ["Protect your peace."], "em": True},
                {"at": round(t0 + span * 0.34, 2), "lines": ["Vibrate your power."], "em": True},
                {"at": round(t0 + span * 0.63, 2),
                 "lines": ["And build what the future", "needs from you."], "em": True},
            ],
        })
    else:
        out.append({
            "kind": "text",
            "from": round(s, 2),
            "to": round(e, 2),
            "beats": [
                {"at": round(AL[g[0]]["start"], 2),
                 "lines": [AL[i]["text"] for i in g],
                 "em": any(i in EMPHASIS for i in g)}
                for g in beats
            ],
        })

body = '''import type { FinishOneConfig } from "../FinishOne";

/**
 * "The Day I Said I Need a Reset" - Serenity Reboot.
 *
 * GENERATED by scripts/build-serenity.py from the measured alignment of
 * Script 02 against the 4:47 recording. Scenes are declared by which script
 * lines they cover, so edit the generator rather than these numbers.
 *
 * All fifteen slides were supplied animated, so every slide scene plays its
 * clip and holds on its last frame if the scene outlasts it.
 */
export const serenityReboot: FinishOneConfig = {
  id: "serenity-reboot",
  audio: "serenity-reboot/narration-with-fx.mp3",
  label: "SERENITY REBOOT",
  endLine: "Something is only urgent if ______",
  durationInSeconds: %s,
  scenes: %s,
};
''' % (TOTAL, json.dumps(out, indent=4, ensure_ascii=False).replace("\n", "\n  "))

(REPO / "remotion/src/modules/serenity-reboot.ts").write_text(body)

slides = sum(1 for s in out if s["kind"] == "slide")
anim = sum(1 for s in out if s.get("video"))
print(f"{len(out)} scenes: {slides} slides ({anim} animated), "
      f"{len(out)-slides} type   total {TOTAL}s")
for s in out:
    tag = pathlib.Path(s.get("image", "")).stem or s["kind"]
    print(f"  {s['from']:7.2f} - {s['to']:7.2f}  {s['kind']:6} {tag}")
