#!/usr/bin/env python3
"""Cut the vertical short from the same alignment, and re-cut its audio.

A five-minute video does not become a Short by cropping it. It has to lose
about eighty percent of its runtime, which means cutting the narration - and
cutting narration is exactly what goes wrong by ear. Every line's start and
end is already measured, so instead the blocks are chosen by which lines they
keep, and every cut lands in the middle of the pause between two lines. A cut
made in silence has no click to hide.

Emits:
  remotion/public/finish-one/narration-short.mp3   the re-cut audio
  remotion/src/modules/finish-one-short.ts         the vertical timeline

Usage:
    python build-finish-one-short.py
"""
import json
import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
AL = json.loads((REPO / "assets/scripts/finish-one-aligned.json").read_text())
NARRATION = REPO / "remotion/public/finish-one/narration.mp3"
OUT_AUDIO = REPO / "remotion/public/finish-one/narration-short.mp3"

# Blocks of consecutive script lines to keep, in order. Chosen to stand alone:
# the hook and its payoff, the question the whole video turns on, and the ask.
BLOCKS = [
    (0, 9),      # "There's a folder..." -> "You need to finish one."
    (46, 49),    # "I stopped asking..." -> "Who do I need to become...?"
    (102, 108),  # "So finish this sentence with me:" -> "...in the comments."
]

# Which still sits behind which lines, in the vertical cut. Lines not covered
# here play as type alone.
STILLS = [
    (4, 9, "02-that-folder"),
    (8, 9, "01-finish-one"),
    (46, 49, "06-the-question"),
    (102, 108, "12-public-promise"),
]

EMPHASIS = {9, 49, 103, 105}


def pause_before(i):
    """Midpoint of the gap in front of line i."""
    if i == 0:
        return max(0.0, AL[0]["start"] - 0.40)
    return (AL[i - 1]["end"] + AL[i]["start"]) / 2


def pause_after(i):
    if i >= len(AL) - 1:
        return AL[i]["end"] + 0.40
    return (AL[i]["end"] + AL[i + 1]["start"]) / 2


def main():
    spans, cursor, remap = [], 0.0, {}
    for lo, hi in BLOCKS:
        src_in, src_out = pause_before(lo), pause_after(hi)
        spans.append((src_in, src_out))
        for k in range(lo, hi + 1):
            remap[k] = {
                "text": AL[k]["text"],
                "start": round(AL[k]["start"] - src_in + cursor, 2),
                "end": round(AL[k]["end"] - src_in + cursor, 2),
            }
        cursor += src_out - src_in

    total = round(cursor, 2)

    # Re-cut the audio. Concatenating inside the pauses means no crossfade is
    # needed and no click is introduced.
    parts = []
    filt = []
    for n, (a, b) in enumerate(spans):
        filt.append(f"[0:a]atrim=start={a:.3f}:end={b:.3f},asetpts=PTS-STARTPTS[a{n}]")
        parts.append(f"[a{n}]")
    filt.append("".join(parts) + f"concat=n={len(spans)}:v=0:a=1[out]")

    subprocess.run(
        ["ffmpeg", "-v", "error", "-i", str(NARRATION),
         "-filter_complex", ";".join(filt), "-map", "[out]",
         "-c:a", "libmp3lame", "-q:a", "2", str(OUT_AUDIO), "-y"],
        check=True)

    measured = float(subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "csv=p=0", str(OUT_AUDIO)],
        capture_output=True, text=True).stdout.strip())
    if abs(measured - total) > 0.25:
        sys.exit(f"audio is {measured:.2f}s but the timeline expects {total:.2f}s")

    # Captions: every kept line, at its time on the new timeline. A Short is
    # watched muted more often than not, so these are not optional.
    captions = [
        {"at": remap[k]["start"], "until": remap[k]["end"],
         "text": remap[k]["text"], "em": k in EMPHASIS}
        for k in sorted(remap)
    ]

    stills = []
    for lo, hi, name in STILLS:
        if lo not in remap:
            continue
        stills.append({
            "image": f"finish-one/slides/{name}.png",
            "from": round(remap[lo]["start"] - 0.35, 2),
            "to": round(remap[hi]["end"] + 0.30, 2),
        })
    stills.sort(key=lambda s: s["from"])

    config = {
        "id": "finish-one-short",
        "audio": "finish-one/narration-short.mp3",
        "durationInSeconds": round(total + 0.6, 2),
        "stills": stills,
        "captions": captions,
    }

    body = '''import type { ShortConfig } from "../FinishOneShort";

/**
 * The vertical cut - Shorts, Reels, TikTok. 1080x1920.
 *
 * GENERATED by scripts/build-finish-one-short.py, which also re-cuts the
 * audio. The blocks it keeps are chosen by script line, and every cut lands
 * in the middle of a pause, so edit the generator rather than these numbers.
 *
 * Captions are burned in because a Short is usually watched muted.
 */
export const finishOneShort: ShortConfig = %s;
''' % json.dumps(config, indent=2, ensure_ascii=False).replace("\n", "\n")

    (REPO / "remotion/src/modules/finish-one-short.ts").write_text(body)

    print(f"audio {measured:.2f}s from {len(spans)} blocks, "
          f"{len(captions)} captions, {len(stills)} stills")
    for (a, b), (lo, hi) in zip(spans, BLOCKS):
        print(f"  {a:7.2f} - {b:7.2f}  ({b-a:5.2f}s)  {AL[lo]['text'][:44]}")


if __name__ == "__main__":
    main()
