import type { ShortConfig } from "../FinishOneShort";

/**
 * The vertical cut - Shorts, Reels, TikTok. 1080x1920.
 *
 * GENERATED by scripts/build-finish-one-short.py, which also re-cuts the
 * audio. The blocks it keeps are chosen by script line, and every cut lands
 * in the middle of a pause, so edit the generator rather than these numbers.
 *
 * Captions are burned in because a Short is usually watched muted.
 */
export const finishOneShort: ShortConfig = {
  "id": "finish-one-short",
  "audio": "finish-one/narration-short.mp3",
  "durationInSeconds": 57.92,
  "stills": [
    {
      "image": "finish-one/slides/02-that-folder.png",
      "from": 8.95,
      "to": 28.49
    },
    {
      "image": "finish-one/slides/01-finish-one.png",
      "from": 24.92,
      "to": 28.49
    },
    {
      "image": "finish-one/slides/06-the-question.png",
      "from": 28.95,
      "to": 41.55
    },
    {
      "image": "finish-one/slides/12-public-promise.png",
      "from": 42.27,
      "to": 57.33
    }
  ],
  "captions": [
    {
      "at": 0.4,
      "until": 2.44,
      "text": "There's a folder on your computer.",
      "em": false
    },
    {
      "at": 3.01,
      "until": 4.4,
      "text": "Maybe it's called Projects.",
      "em": false
    },
    {
      "at": 4.92,
      "until": 7.51,
      "text": "Maybe it's called AI Ideas.",
      "em": false
    },
    {
      "at": 7.51,
      "until": 9.3,
      "text": "Inside that folder?",
      "em": false
    },
    {
      "at": 9.3,
      "until": 13.07,
      "text": "An automation you started on a weekend.",
      "em": false
    },
    {
      "at": 14.04,
      "until": 15.69,
      "text": "A custom GPT you opened once.",
      "em": false
    },
    {
      "at": 16.84,
      "until": 21.67,
      "text": "A Claude project with three brilliant conversations and no finish line.",
      "em": false
    },
    {
      "at": 21.67,
      "until": 24.57,
      "text": "If you keep starting over with AI projects,",
      "em": false
    },
    {
      "at": 25.27,
      "until": 26.88,
      "text": "you don't need another idea.",
      "em": false
    },
    {
      "at": 26.88,
      "until": 28.19,
      "text": "You need to finish one.",
      "em": true
    },
    {
      "at": 29.3,
      "until": 30.27,
      "text": "I stopped asking,",
      "em": false
    },
    {
      "at": 30.27,
      "until": 31.96,
      "text": "\"When will I have enough time?\"",
      "em": false
    },
    {
      "at": 33.19,
      "until": 34.33,
      "text": "And started asking,",
      "em": false
    },
    {
      "at": 35.04,
      "until": 41.25,
      "text": "\"Who do I need to become to keep the promise I made to myself?\"",
      "em": true
    },
    {
      "at": 42.62,
      "until": 44.21,
      "text": "So finish this sentence with me:",
      "em": false
    },
    {
      "at": 44.21,
      "until": 45.64,
      "text": "\"By Day 30, I will have built ______.\"",
      "em": true
    },
    {
      "at": 45.64,
      "until": 46.87,
      "text": "Don't make it impressive.",
      "em": false
    },
    {
      "at": 48.03,
      "until": 49.04,
      "text": "Make it finishable.",
      "em": true
    },
    {
      "at": 49.7,
      "until": 51.62,
      "text": "Too big? Cut it in half.",
      "em": false
    },
    {
      "at": 52.67,
      "until": 54.59,
      "text": "Still too big? Cut it again.",
      "em": false
    },
    {
      "at": 54.59,
      "until": 57.03,
      "text": "Put your sentence in the comments.",
      "em": false
    }
  ]
};
