import type { FinishOneConfig } from "../FinishOne";

/**
 * "The Day I Said I Need a Reset" - Serenity Reboot.
 *
 * GENERATED by scripts/build-serenity.py from the measured alignment of
 * Script 02 against the 4:47 recording. Scenes are declared by which script
 * lines they cover, so edit the generator rather than these numbers.
 *
 * All fifteen slides were supplied animated, so every slide scene plays its
 * clip and holds on its last frame if the scene outlasts it.
 */
export const serenityReboot: FinishOneConfig = {
  id: "serenity-reboot",
  audio: "serenity-reboot/narration-with-fx.mp3",
  label: "SERENITY REBOOT",
  endLine: "Something is only urgent if ______",
  durationInSeconds: 288.27,
  scenes: [
      {
          "kind": "slide",
          "image": "serenity-reboot/slides/01.jpg",
          "from": 0.0,
          "to": 32.88,
          "say": "You know that moment when you open your calendar",
          "video": "serenity-reboot/animations/01.mp4",
          "videoLast": "serenity-reboot/animations/01-last.png",
          "videoSeconds": 10.01
      },
      {
          "kind": "text",
          "from": 32.88,
          "to": 60.92,
          "beats": [
              {
                  "at": 33.96,
                  "lines": [
                      "It was a Monday that felt like a Friday."
                  ],
                  "em": false
              },
              {
                  "at": 36.4,
                  "lines": [
                      "Client work.",
                      "Content.",
                      "Family commitments."
                  ],
                  "em": false
              },
              {
                  "at": 41.8,
                  "lines": [
                      "Messages I hadn't answered."
                  ],
                  "em": false
              },
              {
                  "at": 43.04,
                  "lines": [
                      "I kept jumping between tasks."
                  ],
                  "em": false
              },
              {
                  "at": 45.8,
                  "lines": [
                      "Starting.",
                      "Stopping.",
                      "Starting again."
                  ],
                  "em": false
              },
              {
                  "at": 47.64,
                  "lines": [
                      "Ten hours of busy.",
                      "Nothing that mattered had moved."
                  ],
                  "em": true
              },
              {
                  "at": 51.12,
                  "lines": [
                      "And I remember thinking,",
                      "\"I don't need another planner."
                  ],
                  "em": false
              },
              {
                  "at": 55.28,
                  "lines": [
                      "I need someone to tell me what can wait.\""
                  ],
                  "em": true
              },
              {
                  "at": 58.84,
                  "lines": [
                      "That sentence became a project."
                  ],
                  "em": true
              }
          ]
      },
      {
          "kind": "slide",
          "image": "serenity-reboot/slides/02.jpg",
          "from": 60.92,
          "to": 83.12,
          "say": "Maybe that's your week right now.",
          "video": "serenity-reboot/animations/02.mp4",
          "videoLast": "serenity-reboot/animations/02-last.png",
          "videoSeconds": 10.01
      },
      {
          "kind": "slide",
          "image": "serenity-reboot/slides/03.jpg",
          "from": 83.12,
          "to": 92.25,
          "say": "And when our own calendar breaks,",
          "video": "serenity-reboot/animations/03.mp4",
          "videoLast": "serenity-reboot/animations/03-last.png",
          "videoSeconds": 10.01
      },
      {
          "kind": "slide",
          "image": "serenity-reboot/slides/05.jpg",
          "from": 92.25,
          "to": 101.52,
          "say": "So I entered a hackathon.",
          "video": "serenity-reboot/animations/05.mp4",
          "videoLast": "serenity-reboot/animations/05-last.png",
          "videoSeconds": 10.01
      },
      {
          "kind": "slide",
          "image": "serenity-reboot/slides/04.jpg",
          "from": 101.52,
          "to": 105.02,
          "say": "\"I need a reset.\"",
          "video": "serenity-reboot/animations/04.mp4",
          "videoLast": "serenity-reboot/animations/04-last.png",
          "videoSeconds": 10.01
      },
      {
          "kind": "slide",
          "image": "serenity-reboot/slides/06.jpg",
          "from": 105.02,
          "to": 119.12,
          "say": "The system reads the next seventy-two hours of your calendar and email.",
          "video": "serenity-reboot/animations/06.mp4",
          "videoLast": "serenity-reboot/animations/06-last.png",
          "videoSeconds": 10.01
      },
      {
          "kind": "slide",
          "image": "serenity-reboot/slides/07.jpg",
          "from": 119.12,
          "to": 130.49,
          "say": "Then a short video plays.",
          "video": "serenity-reboot/animations/07.mp4",
          "videoLast": "serenity-reboot/animations/07-last.png",
          "videoSeconds": 10.01
      },
      {
          "kind": "slide",
          "image": "serenity-reboot/slides/08.jpg",
          "from": 130.49,
          "to": 140.51,
          "say": "Here's what nobody tells you about building your first AI tool.",
          "video": "serenity-reboot/animations/08.mp4",
          "videoLast": "serenity-reboot/animations/08-last.png",
          "videoSeconds": 10.01
      },
      {
          "kind": "slide",
          "image": "serenity-reboot/slides/09.jpg",
          "from": 140.51,
          "to": 158.45,
          "say": "I had to decide what urgent actually means.",
          "video": "serenity-reboot/animations/09.mp4",
          "videoLast": "serenity-reboot/animations/09-last.png",
          "videoSeconds": 10.01
      },
      {
          "kind": "slide",
          "image": "serenity-reboot/slides/10.jpg",
          "from": 158.45,
          "to": 170.07,
          "say": "Serenity Reboot took first place.",
          "video": "serenity-reboot/animations/10.mp4",
          "videoLast": "serenity-reboot/animations/10-last.png",
          "videoSeconds": 10.01
      },
      {
          "kind": "slide",
          "image": "serenity-reboot/slides/11.jpg",
          "from": 170.07,
          "to": 200.06,
          "say": "Maybe you're thinking,",
          "video": "serenity-reboot/animations/11.mp4",
          "videoLast": "serenity-reboot/animations/11-last.png",
          "videoSeconds": 10.01
      },
      {
          "kind": "slide",
          "image": "serenity-reboot/slides/12.jpg",
          "from": 200.06,
          "to": 218.54,
          "say": "I'm locking in for 100 days.",
          "video": "serenity-reboot/animations/12.mp4",
          "videoLast": "serenity-reboot/animations/12-last.png",
          "videoSeconds": 10.01
      },
      {
          "kind": "slide",
          "image": "serenity-reboot/slides/13.jpg",
          "from": 218.54,
          "to": 226.61,
          "say": "Serenity Reboot started exactly the way your next project could start.",
          "video": "serenity-reboot/animations/13.mp4",
          "videoLast": "serenity-reboot/animations/13-last.png",
          "videoSeconds": 10.01
      },
      {
          "kind": "text",
          "from": 226.61,
          "to": 236.86,
          "beats": [
              {
                  "at": 227.32,
                  "lines": [
                      "The link is below."
                  ],
                  "em": false
              },
              {
                  "at": 228.92,
                  "lines": [
                      "It's my affiliate link, so I earn a portion of your membership if you join. I want you to know that."
                  ],
                  "em": false
              }
          ]
      },
      {
          "kind": "slide",
          "image": "serenity-reboot/slides/14.jpg",
          "from": 236.86,
          "to": 265.88,
          "say": "Now think about the thing that drains you every week.",
          "video": "serenity-reboot/animations/14.mp4",
          "videoLast": "serenity-reboot/animations/14-last.png",
          "videoSeconds": 10.01
      },
      {
          "kind": "slide",
          "image": "serenity-reboot/slides/15.jpg",
          "from": 265.88,
          "to": 282.46,
          "say": "So let's do this together.",
          "video": "serenity-reboot/animations/15.mp4",
          "videoLast": "serenity-reboot/animations/15-last.png",
          "videoSeconds": 10.01
      },
      {
          "kind": "end",
          "from": 282.46,
          "to": 288.27,
          "beats": [
              {
                  "at": 282.48,
                  "lines": [
                      "Protect your peace."
                  ],
                  "em": true
              },
              {
                  "at": 284.14,
                  "lines": [
                      "Vibrate your power."
                  ],
                  "em": true
              },
              {
                  "at": 285.55,
                  "lines": [
                      "And build what the future",
                      "needs from you."
                  ],
                  "em": true
              }
          ]
      }
  ],
};
